/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/old-pc.glb 
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";
import {Vector3} from "three";

export function Model(props) {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('models/old-pc.glb')
    const {actions} = useAnimations(animations, group)

    useEffect(() => {
        actions["keyboardAction"].play()
        actions["mouseAction"].play()
    }, [])

    useFrame((state) => {
        group.current.rotation.y = Math.sin((state.clock.elapsedTime)/4)
    })

    return (
        <>
            <group ref={group} {...props} dispose={null} position={[0,-2,0]}>
                <group name="Scene">
                    <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="d2983d5b5005429484219be2711030e6fbx" rotation={[-Math.PI / 2, 0, 0]} scale={0.016}>
                            <group name="RootNode">
                                <group name="Cube" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                    <mesh name="Cube_BakedPCBody_0" geometry={nodes.Cube_BakedPCBody_0.geometry}
                                          material={materials['BakedPCBody.001']}/>
                                    <mesh name="Cube_BakedScreen_0" geometry={nodes.Cube_BakedScreen_0.geometry}
                                          material={materials['BakedScreen']}/>
                                </group>
                                <group name="Cube003" position={[0, 0, 167.586]} rotation={[-Math.PI / 2, 0, 0]}
                                       scale={13.106}>
                                    <mesh name="keyboard"
                                          geometry={nodes.keyboard.geometry}
                                          material={materials['BakedMouseKeyboard.001']} position={[-17.028, -4.432, 8.047]}
                                          rotation={[0, -0.338, 0]}/>
                                </group>
                                <group name="Cube004" position={[0, 0, 167.586]} rotation={[-Math.PI / 2, 0, 0]}
                                       scale={13.106}>
                                    <mesh name="mouse"
                                          geometry={nodes.mouse.geometry}
                                          material={materials['BakedMouseKeyboard.001']} position={[15.022, -2.629, 7.465]}
                                          rotation={[0.223, -0.629, 0.65]}/>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </>
    )
}

useGLTF.preload('models/old-pc.glb')
